### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by 14w** [4ksr/PacketSniffer#1]
# About

This project is designed to perform network packet sniffing and analysis. While the code runs successfully on some devices, it may encounter issues when executed on certain macOS systems or across multiple devices concurrently. 

## Issue Description

The "not work in Multiple devices" issue arises when attempting to run the code on macOS systems or when trying to execute it simultaneously on multiple devices. This issue could be due to various factors, including compatibility issues with specific macOS versions, limitations of the PcapDotNet library on macOS, or conflicts with other network-related software running on the system.

## Resolution

Addressing this issue requires further investigation and potential modifications to the codebase to improve compatibility with macOS systems and ensure robustness when running on multiple devices. Possible steps to resolve the issue include:

- Investigating compatibility of the PcapDotNet library with macOS and identifying any known limitations or workarounds.
- Checking for any system-specific dependencies or configurations required for proper execution on macOS.
- Debugging and testing the code on different macOS versions and configurations to identify the root cause of the issue.
- Implementing platform-specific adjustments or alternative solutions to ensure cross-device compatibility.

## Contributions

Contributions to address the "not work in Multiple devices" issue are welcome. Feel free to submit bug reports, feature requests, or pull requests on the GitHub repository to help improve the compatibility and usability of the project across different environments.

**Comment by 4ksr** [comment]
> # About
> 
> This project is designed to perform network packet sniffing and analysis. While the code runs successfully on some devices, it may encounter issues when executed on certain macOS systems or across multiple devices concurrently.
> ## Issue Description
> 
> The "not work in Multiple devices" issue arises when attempting to run the code on macOS systems or when trying to execute it simultaneously on multiple devices. This issue could be due to various factors, including compatibility issues with specific macOS versions, limitations of the PcapDotNet library on macOS, or conflicts with other network-related software running on the system.
> ## Resolution
> 
> Addressing this issue requires further investigation and potential modifications to the codebase to improve compatibility with macOS systems and ensure robustness when running on multiple devices. Possible steps to resolve the issue include:
> 
>     * Investigating compatibility of the PcapDotNet library with macOS and identifying any known limitations or workarounds.
> 
>     * Checking for any system-specific dependencies or configurations required for proper execution on macOS.
> 
>     * Debugging and testing the code on different macOS versions and configurations to identify the root cause of the issue.
> 
>     * Implementing platform-specific adjustments or alternative solutions to ensure cross-device compatibility.
> 
> 
> ## Contributions
> 
> Contributions to address the "not work in Multiple devices" issue are welcome. Feel free to submit bug reports, feature requests, or pull requests on the GitHub repository to help improve the compatibility and usability of the project across different environments.

# Response

Thank you for bringing this to our attention! We appreciate your feedback and understanding. Our team is actively working on resolving the issue to ensure that the project runs smoothly across multiple devices, including macOS systems. We will prioritize addressing this concern and provide updates on our progress soon. Your patience and support are greatly appreciated.

In the meantime, if you have any further questions or suggestions, please feel free to reach out. We're committed to delivering the best possible experience for our users, and your input helps us achieve that goal.

Best regards,
ksr
